default:
  interruptible: true

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  PY_COLORS: 1

test:
  image: python:${PYTHON_VERSION}
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
  script:
    - pip install tox
    - tox -e py3
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: test.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint:
  image: python:3.11
  script:
    - pip install tox
    - tox -e flake8,pylint
